#!/usr/bin/env python3
"""turn a Ghidra function export into an ndsdisasm config"""

import argparse
import re
import sys

ENTRY_RE = re.compile(r'^\s*(arm_func|thumb_func)\s+(0x[0-9a-fA-F]+)\s*(\S*)')


def parse(path):
    out = []
    with open(path) as handle:
        for line in handle:
            match = ENTRY_RE.match(line)
            if match:
                kind, addr, name = match.groups()
                out.append((kind, int(addr, 16), name or None))
    return out


def alignment_ok(kind, address):
    return address % 4 == 0 if kind == 'arm_func' else address % 2 == 0


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('export', help="Ghidra export in ndsdisasm format")
    parser.add_argument('-o', '--output', required=True)
    parser.add_argument('--merge', action='append', default=[],
                        help="additional config to merge in (may repeat)")
    parser.add_argument('--load', required=True, help="load address, e.g. 0x02004000")
    parser.add_argument('--size', required=True, help="module size, e.g. 0x6F898")
    parser.add_argument('--entry', help="entry point; entries below it are dropped")
    parser.add_argument('--header-size', default='0',
                        help="secure-area header size to mark as data")
    parser.add_argument('--title', default='ndsdisasm configuration')
    args = parser.parse_args()

    load = int(args.load, 16)
    size = int(args.size, 16)
    end = load + size
    header = int(args.header_size, 16)
    floor = int(args.entry, 16) if args.entry else load

    entries = {}
    stats = {'range': 0, 'header': 0, 'align': 0, 'dupe': 0}

    for source in [args.export] + args.merge:
        for kind, address, name in parse(source):
            if not (load <= address < end):
                stats['range'] += 1
                continue
            if address < floor:
                stats['header'] += 1
                continue
            if not alignment_ok(kind, address):
                stats['align'] += 1
                continue
            if address in entries:
                stats['dupe'] += 1
                continue
            entries[address] = (kind, name or f"sub_{address:08X}")

    lines = [
        f"# {args.title}",
        "# Format: <type> <address> [name]",
        "#",
        f"# Load 0x{load:08X}  size 0x{size:X}  entry 0x{floor:08X}",
        "# Generated by tools/scripts/make_ndsdisasm_config.py",
        "",
    ]

    if header:
        lines += [
            "# Secure area header - not code",
            f"data 0x{load:08X}",
            "",
        ]

    for address in sorted(entries):
        kind, name = entries[address]
        lines.append(f"{kind} 0x{address:08x} {name}")

    with open(args.output, 'w') as handle:
        handle.write("\n".join(lines) + "\n")

    arm = sum(1 for kind, _ in entries.values() if kind == 'arm_func')
    thumb = len(entries) - arm

    print(f"wrote {len(entries)} entries to {args.output}")
    print(f"  arm:   {arm}")
    print(f"  thumb: {thumb}")
    print(f"dropped: {stats['range']} out of range, {stats['header']} below entry, "
          f"{stats['align']} misaligned, {stats['dupe']} duplicate")


if __name__ == '__main__':
    sys.exit(main())
